Improvement/feedback
InfrastructureEducationPlatform/platform_plugin pull request #1
Opened 2024-02-13 13:42 UTC by choish19

2024-02-13 14:31 UTC, KangDroid requested changes

2024-02-13 14:31 UTC, KangDroid commented on src/main/kotlin/com/example/demo/web/WebApiService.kt
> +    val log = KotlinLogging.logger {}
기본 제공되어 있는 Springboot의 Default Logger 대신에 KotlinLogging을 추가 설치한 이유가 있을지!

```kotlin
class Foo {
    private val logger: Logger = LoggerFactory.getLogger("logger-name"); // logger name은 보통 클래스 이름, this::class.java 이렇게 쓰기도 할걸..? 아마도?
    fun bar() { logger.info(""); logger.trace(""); } 등등
}
```

자세한 내용은 [이 링크](https://loosie.tistory.com/829) 를 참고해 보시죱

2024-02-13 15:54 UTC, choish19 commented on src/main/kotlin/com/example/demo/web/WebApiService.kt
> +    val log = KotlinLogging.logger {}
노션 피드백에 있는 logger 링크는 자바코드라 코틀린 logger에 대해 찾아보니 코틀린 logger를 지원하는 라이브러리가 있어서 활용해봤어. 아무래도 코틀린 기반 코드라 코틀린에서 logger를 지원하는 라이브러리가 동작에는 조금 더 유리하진 않을까?

2024-02-13 23:26 UTC, KangDroid commented on src/main/kotlin/com/example/demo/web/WebApiService.kt
> +    val log = KotlinLogging.logger {}
봤는데 kotlin-logger이 나온 배경에 꽤 공감이 가긴 하네. 다만 저렇게 접근하면 spring의 logback이나 sl4fj와 연동이 실제로 되는건지?

왜냐면 spring의 로그백같은 경우에는 로그 자체를 확장(i.e console표시 뿐만 아니라 ES/DB/File등에 동시 sink하는 등)할 수 있는데, kotlin-logger은 그게 가능한지 모르겠어 - 사실 logback추가해서 몇가지 테스트 하면 되긴 하는데, 당장 우선순위는 아니니까 이거 PoC는 백로그에 남겨주십셔

그리고 사용한 라이브러리를 어디서 레퍼런스를 가져온건지 모르겠지만... 많이 옛날 버전이고 outdated버전으로 보이는데 함 확인해 주시져

[공식 깃헙](https://github.com/oshai/kotlin-logging?tab=readme-ov-file)

[공식 위키](https://github.com/oshai/kotlin-logging/wiki)


그리고 제 3자가 쓴 블로그는 1차 이해/오버뷰로 활용하고 실제 사용은 꼭 공식 문서를 확인하는게 좋을듯! 많은 블로그의 경우는 글이 업데이트가 안되다 보니까 outdate된 내용들이 (특히 한국은 더더욱...) 많슴다

2024-02-13 23:27 UTC, KangDroid commented on src/main/kotlin/com/example/demo/web/WebApiService.kt
> +    val log = KotlinLogging.logger {}
일단 라이브러리 최신화 하시고 머지 ㄱㄱ 하시죠!

2024-02-13 23:27 UTC, KangDroid approved these changes

2024-02-14 12:39 UTC, choish19 commented on src/main/kotlin/com/example/demo/web/WebApiService.kt
> +    val log = KotlinLogging.logger {}
오키 확인했어. 다음에는 공식 문서 확인하고 조금 더 검증해서 코드 작성하겠습니다. 레퍼런스 확인하고 일단 PoC는 백로그에 남겨둘게. 나머지 라이브러리 최신화하고 머지한 다음 에러 처리 작업할게

2024-02-14 13:18 UTC, merged